### ISSUE TITLE
Add new mixpanel events for tracking feature effectiveness

### ISSUE THREAD

**Issue by dvenga** [juspay/hyperswitch-control-center#156]
Refactor the mixpanel code and add the following events to track:

Landing page:

- [ ] Sign up link
- [ ] Sign in using password link
- [ ] Continue with email button

Home Page:

- [ ] Get production access (nav bar)
- [ ] Self serve primary button (Configure test mode, integrate into app, get production access)
- [ ] Stripe + PayPal tile
- [ ] Woocommerce tile
- [ ] Try test payment
- [ ] Contribute to open source
- [ ] Dev docs

Payments / Refunds / Disputes Page 

- [ ] Generate sample data
- [ ] Generate reports

Analytics Page:
- [ ] Generate reports

Routing
- [ ] Setup volume based routing
- [ ] Setup rule based routing
- [ ] Manage fallback

3DS
- [ ] Create new 

API Key
- [ ] Create new API Key

Team
- [ ] Invite users
