### ISSUE TITLE
[Enhance] : Analytics

### ISSUE THREAD

**Issue by JeevaRamu0104** [juspay/hyperswitch-control-center#649]
- [x] https://github.com/juspay/hyperswitch-control-center/issues/633
- [ ] https://github.com/juspay/hyperswitch-control-center/issues/685
- [ ] https://github.com/juspay/hyperswitch-control-center/issues/755
- [ ] [Add only relevant dimensions for each segment. For example success rate dimension makes no sense for Status segment](https://github.com/juspay/hyperswitch-control-center/issues/756)
- [ ] [For payment method type, cards are going under Other](https://github.com/juspay/hyperswitch-control-center/issues/757)
- [x]  [Remove currency related metrics as the hero metrics till we have currency conversion module. Ask designers how to differentiate these as primary and secondary metrics](https://github.com/juspay/hyperswitch-control-center/issues/758)
<img width="949" alt="image" src="https://github.com/juspay/hyperswitch-control-center/assets/120017870/03530d02-cfe9-493c-866c-801091e5a493">

<img width="934" alt="image" src="https://github.com/juspay/hyperswitch-control-center/assets/120017870/1c1ba2fd-3eb8-4773-813a-f1b4d7c8519e">
<img width="813" alt="image" src="https://github.com/juspay/hyperswitch-control-center/assets/120017870/4a73178f-dfc8-4194-b52f-a53102b88c92">
<img width="921" alt="image" src="https://github.com/juspay/hyperswitch-control-center/assets/120017870/705d47c6-ff7f-45da-88ef-1d7bafddbe1b">

**Comment by bernard-eugine** [comment]
@JeevaRamu0104 @sagarnaikjuspay https://github.com/juspay/hyperswitch-control-center/issues/766
